name: Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12' ]

    steps:
      # check-out repo
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.8.4
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --with dev
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          poetry run make lint
